Hw7 threadpool
Xrite/java-hw-2-course pull request #11
Opened 2019-05-01 00:42 UTC by Xrite

2019-05-02 17:07 UTC, Xrite commented
Почему-то на travis все внезапно сломалось, т.е. даже старые лабы теперь не работают.

2019-05-04 22:10 UTC, RamSaw commented
> Почему-то на travis все внезапно сломалось, т.е. даже старые лабы теперь не работают.

у Вас по всей видимости проблемы с gradle wrapper. Поэтому gradlew падает. Пофиксите уж. Попробуйте вызывать системный gradle. Возможно он работает.

2019-05-04 22:36 UTC, RamSaw requested changes
@Xrite проверил.

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/main/java/LightFuture.java
> +    T get() throws InterruptedException, LightExecutionException;
InterruptedException?

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +    private volatile boolean isShutdown = false;
зачем volatile?

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +                worker.interrupt();
join еще лучше сделать

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +                    thenApplyTasks.wait();
spurious wakeups

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +        public T get() throws InterruptedException, LightExecutionException {
кажется, что get может работать бесконечно: я делаю submit, shutdown, а потом get. Как итог, task не успела выполниться, все воркеры уже мертвы и она будет висеть. Или я где-то ошибся?

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +            var task = new Task<V>(() -> function.apply(result));
а что если в родителе случилось exception?

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +                wait();
spurious wakeups

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        Thread.sleep(1000);
зачем спать?

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        assertThrows(LightExecutionException.class, () -> future.thenApply(Object::toString).get());
ассерт проходит не потому, что там RuntimeException, а потому что Object::toString на null кидает NPE. Так что давайте в тестах проверять cause у exception.

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        var future = pool.submit(() -> 0);
не используемая переменная -1.

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        Thread.sleep(1000);
мб лучше вызвать get и проверить, что потом оно тру? еще надо бы проверить, что False порой бывает. Вот тут без sleep вряд ли как-то получится.

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        Thread.sleep(1000);
тут лучше get, а не sleep.

2019-05-04 22:36 UTC, RamSaw commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        assertTrue(4 <= names.size());
assertEquals мб?

2019-05-17 19:03 UTC, Xrite commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +    private volatile boolean isShutdown = false;
Чтобы HB было. Иначе может отправится задача после shutdown.

2019-05-17 19:08 UTC, Xrite commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +                    thenApplyTasks.wait();
Хм, кажется, что я здесь их обработал.

2019-05-17 19:13 UTC, Xrite commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +        public T get() throws InterruptedException, LightExecutionException {
В задании вроде было указано просто вызывать interrupt у worker. Да, она будет висеть.

2019-05-17 19:16 UTC, Xrite commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        var future = pool.submit(() -> 0);
Тут я не согласен, она же используется в assert.

2019-05-17 19:19 UTC, Xrite commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        assertTrue(4 <= names.size());
Тут я не придумал как хорошо это тестировать. Я хотел проверить, что работает многопоточность. Изначально я запускал на 8 потоках и смотрел, что все 8 работали. Но такой тест, к сожалению, падал, и это вполне нормально, может быть такое, что работали всего 7 или даже 6 потоков, поэтому я поставил неравенство. Может это можно как-то получше сделать?

2019-05-17 19:53 UTC, Xrite commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        assertThrows(LightExecutionException.class, () -> future.thenApply(Object::toString).get());
Исправил.

2019-05-17 19:54 UTC, Xrite commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +            var task = new Task<V>(() -> function.apply(result));
Исправил, теперь будет родительское исключение.

2019-05-17 19:55 UTC, Xrite commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +                wait();
Кажется, что тут тоже это обработано. Либо я что-то не понял.

2019-05-17 20:03 UTC, Xrite commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        Thread.sleep(1000);
Действительно, не надо.

2019-05-17 20:19 UTC, Xrite commented on 7-ThreadPool/src/main/java/LightFuture.java
> +    T get() throws InterruptedException, LightExecutionException;
Убрал.

2019-05-17 20:19 UTC, Xrite commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +                worker.interrupt();
Сделал.

2019-05-17 20:21 UTC, Xrite commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        var future = pool.submit(() -> 0);
А, ок, нашел в другой функции.

2019-05-22 13:34 UTC, RamSaw requested changes
@Xrite тест на n потоков остался. Остальное все круто.

2019-05-22 13:34 UTC, RamSaw commented on 7-ThreadPool/src/main/java/ThreadPool.java
> +                while (worker.isAlive()) {
https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#join(long) кажется, что в join это уже реализовано, так что можно спокойно join вызывать без опасений по поводу spurious wakeups.

2019-05-22 13:34 UTC, RamSaw commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        assertTrue(4 <= names.size());
Подождите, но если спать долго в Таске, то должны заработать все потоки в пуле.
Сделайте мб 4 потока, а не 8. Но вообще странно, и 8 должно работать. Тем более что у Вас Thread.sleep(10000000); был раньше. Но 10000000 как-то уж совсем много, 1 секунды должно быть достаточно.

2019-05-22 13:34 UTC, RamSaw commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        System.out.println(names.size());
Ну и когда будет assertEquals этот принт не будет нужен вообще.

2019-06-10 14:15 UTC, Xrite commented on 7-ThreadPool/src/test/java/ThreadPoolTest.java
> +        System.out.println(names.size());
Да, я поправил, проблемы были из-за того, что я забыл синхронизироваться по сету, когда в него добавляю что-нибудь.

2019-06-13 09:53 UTC, RamSaw approved these changes
@Xrite все ок
@jzuken

2019-06-13 12:03 UTC, merged