Hw8 cannon
Xrite/java-hw-2-course pull request #14
Opened 2019-05-31 16:35 UTC by Xrite

2019-06-04 12:34 UTC, RamSaw commented
@Xrite пофиксите travis пока. На днях посмотрю сам код.

2019-06-05 15:23 UTC, Xrite commented
@RamSaw Я не знаю, это что-то travis глючит. Он не справился java поставить.

2019-06-09 08:11 UTC, RamSaw requested changes
@Xrite проверил жду исправлений

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Cannon.java
> +        if(newX <= landscape.getMaxX()) {
пробел.

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/settings.gradle
> +rootProject.name = 'cannon'
у вас слишком редко происходит рендеринг и проверка столкновения снаряда с ландшафтом. Из-за этого снаряд перелетает сквозь тонкую гору.

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Cannon.java
> +        return new Projectile(position.add(barrelVector), barrelVector.normalize().multiply(5), powerFactor, landscape);
что такое 5? назовите это как-то.

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Cannon.java
> +        var barrelVector = new Point2D(Math.cos(angle), Math.sin(angle)).multiply(BARREL_LENGTH);
два раза строчка повторяется, выделите в отдельный метод тогда уж.

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Explosion.java
> +        return target.getCenter().distance(center) <= radius * currentStage;
кажется тут не учитывается радиус самой цели

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Game.java
> +
пустая строчка здесь ни к чему

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Game.java
> +        Set<KeyCode> keys = new HashSet<>();
а почему Set а не List?

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Game.java
> +            int projectileType = 0;
это наверное должно быть статичным полем класса игры и называется DEFAULT_PROJECTILE_STRENGTH или как-то так. Это же кстати не тип у Вас, а сила пули.

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Game.java
> +                if (keys.contains(KeyCode.LEFT)) {
мб проитерироваться по множеству и сделать switch внутри.
И еще этот метод надо разбить на несколько методов, он слишком большой.

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Renderer.java
> +        scaleFactor = screenWidth / widthInMeters;
лучше поменять эти строчки местами и уже использовать scaleFactor, и не делить два числа два раза.

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Renderer.java
> +                new double[]{transformY(begin.getY()), transformY(end.getY()), transformY(0), transformY(0)}, 4);
что такое 4?

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Renderer.java
> +
пустая строчка.

2019-06-09 08:11 UTC, RamSaw commented on 8-Cannon/src/main/java/Target.java
> +        renderer.drawCircle(center, radius / 3.0, Color.RED);
blueFraction = 1, yellowFraction = 2.0 / 3.0, redFraction = 1.0 / 3.0 и это лучше сделать статическими константами класса.

2019-06-10 12:40 UTC, Xrite commented on 8-Cannon/src/main/java/Cannon.java
> +        if(newX <= landscape.getMaxX()) {
Исправил

2019-06-10 13:01 UTC, Xrite commented on 8-Cannon/settings.gradle
> +rootProject.name = 'cannon'
Там проблема, что в AnimationTimer это не особо настраивается, поэтому скажем, что это не бага, а фича.

2019-06-10 13:03 UTC, Xrite commented on 8-Cannon/src/main/java/Cannon.java
> +        return new Projectile(position.add(barrelVector), barrelVector.normalize().multiply(5), powerFactor, landscape);
Исправил

2019-06-10 13:04 UTC, Xrite commented on 8-Cannon/src/main/java/Explosion.java
> +        return target.getCenter().distance(center) <= radius * currentStage;
Да, нужно чтобы достало центр, так и задумывалось изначально.

2019-06-10 13:05 UTC, Xrite commented on 8-Cannon/src/main/java/Game.java
> +
Убрал

2019-06-10 13:06 UTC, Xrite commented on 8-Cannon/src/main/java/Game.java
> +        Set<KeyCode> keys = new HashSet<>();
Чтобы два раза нажатия на одни и те же кнопки не учитывать.

2019-06-10 13:17 UTC, Xrite commented on 8-Cannon/src/main/java/Game.java
> +            int projectileType = 0;
Ну сила и тип в каком-то смысле одно и то же.

2019-06-10 13:57 UTC, Xrite commented on 8-Cannon/src/main/java/Game.java
> +                if (keys.contains(KeyCode.LEFT)) {
Исправил

2019-06-10 14:00 UTC, Xrite commented on 8-Cannon/src/main/java/Renderer.java
> +        scaleFactor = screenWidth / widthInMeters;
Исправил

2019-06-10 14:00 UTC, Xrite commented on 8-Cannon/src/main/java/Renderer.java
> +                new double[]{transformY(begin.getY()), transformY(end.getY()), transformY(0), transformY(0)}, 4);
Исправил

2019-06-10 14:01 UTC, Xrite commented on 8-Cannon/src/main/java/Renderer.java
> +
Убрал

2019-06-10 14:04 UTC, Xrite commented on 8-Cannon/src/main/java/Target.java
> +        renderer.drawCircle(center, radius / 3.0, Color.RED);
Сделал

2019-06-13 09:47 UTC, RamSaw commented on 8-Cannon/settings.gradle
> +rootProject.name = 'cannon'
Надо тогда не генерить тонкие горы :). Но да ладно, пусть будет так. Просто ваши сокурсники тоже писали на AnimationTimer и я у них такого не увидел и было все довольно реалистично.

2019-06-13 09:50 UTC, RamSaw requested changes
@Xrite одно замечание не пофиксили

2019-06-13 09:50 UTC, RamSaw commented on 8-Cannon/src/main/java/Cannon.java
> +        var barrelVector = new Point2D(Math.cos(angle), Math.sin(angle)).multiply(BARREL_LENGTH);
вы кажется это не исправили...

2019-06-13 17:29 UTC, RamSaw approved these changes
@Xrite все ок
@jzuken

2019-06-14 08:21 UTC, merged