Hw9 myjunit
Xrite/java-hw-2-course pull request #15
Opened 2019-06-02 20:02 UTC by Xrite

2019-06-08 07:11 UTC, jzuken requested changes

2019-06-08 07:11 UTC, jzuken commented on 9-MyJUnit/src/main/java/annotations/Test.java
> +    Class<? extends Throwable> exception() default NoException.class;
а тут доки? 
-0.5

2019-06-08 07:11 UTC, jzuken commented on 9-MyJUnit/src/main/java/Testing.java
> +            (Method method) -> method.isAnnotationPresent(BeforeClass.class),
а в реальном junit'е эти методы должны быть статическими, наверное и тут тоже стоит так сделать

2019-06-08 07:11 UTC, jzuken commented on 9-MyJUnit/src/main/java/Testing.java
> +     *                          or testing method has arguments or method that is not annotated with @Test throws an exception or some unexpected
длинновата строка

2019-06-08 07:11 UTC, jzuken commented on 9-MyJUnit/src/main/java/Testing.java
> +            return tests.stream().filter(test -> test instanceof TestingSummary.MethodSummary.Passed).map(test -> (MethodSummary.Passed) test).collect(Collectors.toList());
и тут

2019-06-10 12:11 UTC, Xrite commented on 9-MyJUnit/src/main/java/Testing.java
> +            (Method method) -> method.isAnnotationPresent(BeforeClass.class),
Не очень понял замечание. И вообще, какая разница будет от этого? Это же вроде ничего существенно не меняет.

2019-06-10 12:12 UTC, Xrite commented on 9-MyJUnit/src/main/java/annotations/Test.java
> +    Class<? extends Throwable> exception() default NoException.class;
Так к ним описания написанны в описании класса.

2019-06-10 12:17 UTC, Xrite commented on 9-MyJUnit/src/main/java/Testing.java
> +     *                          or testing method has arguments or method that is not annotated with @Test throws an exception or some unexpected
Исправил

2019-06-10 12:17 UTC, Xrite commented on 9-MyJUnit/src/main/java/Testing.java
> +            return tests.stream().filter(test -> test instanceof TestingSummary.MethodSummary.Passed).map(test -> (MethodSummary.Passed) test).collect(Collectors.toList());
Исправил

2019-06-12 09:30 UTC, jzuken commented on 9-MyJUnit/src/main/java/annotations/Test.java
> +    Class<? extends Throwable> exception() default NoException.class;
ну при генерации фигня же будет, если на метод нажать, у него ничего не покажется

2019-06-12 09:32 UTC, jzuken commented on 9-MyJUnit/src/main/java/Testing.java
> +            (Method method) -> method.isAnnotationPresent(BeforeClass.class),
не меняет, просто добавятся ещё несколько проверок и схема становится чуть более сложной

2019-06-14 08:21 UTC, merged