Hw2 trie
Xrite/java-hw-2-course pull request #2
Opened 2019-02-04 14:02 UTC by Xrite

2019-02-04 15:50 UTC, RamSaw requested changes
@Xrite, домашку проверил. Как пофиксите или напишите контраргументы (не стесняйтесь спорить аргументированно, я тоже могу ошибаться), упомяните меня через "@RamSaw". У меня, к сожалению, доступа к hwproj нет, поэтому так поступим. Но если увижу на hwproj, что Вы пофиксили, то тоже посмотрю. Еще исправьте, пожалуйста, merge конфликт у gitignore.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +public class Trie {
Надо выделить интерфейс Serializable, еще кстати можно выделить в отдельный интерфейс публичные методы бора. А этот Trie будет реализацией этих двух интерфейсов.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +    public Trie() {
Можно провести эту инициализацию сразу при объявлении полей.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +    Trie simpleTrie() {
Сделайте его private. И заодно пустую строчку выше удалите :).

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +    void size() {
Я бы добавил еще парочку add, чтобы проверить, что размер увеличивается.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +    void checkId(Trie trie, String[] strings) throws IOException {
Давайте сделаем имя более понятное, checkIdentity к примеру. И проверку size двух trie добавим. Или еще лучше перегрузить equals у Trie и просто написать assertEquals на них. Тогда и необходимость этого метода пропадет. И протестировать equals тоже надо будет.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +        String[] simpleStrings = {"aba", "caba", "abab", "abacaba", "abracadabra", "baca", ""};
Это те же строки, что и в simpleTrie. Давайте их вынесем в поле класса, к примеру. Чтобы менять в одном месте пришлось, а не в двух.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +    void serialize() throws IOException {
Вообще тест можно разбить на два: serializeEmpty и serializeNotEmpty.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +    void deserialize() {
Зачем пустой тест? Надо убрать. А вообще совсем круто было бы тестить serialize и deserialize независимо друг от друга. Но и совместный тест тоже можно оставить.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +            if (currentNode.getTransition(c) == null) {
Очень хорошее решение выделить такие функции у Node :+1:

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +    private Node root;
Сюда аннотацию тоже можно добавить.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +        private HashMap<Character, Node> transition = new HashMap<Character, Node>();
new HashMap<Character, Node> - можно просто new HashMap<>.

2019-02-04 15:50 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +        private Node addTransition(char c) {
можно не возвращать Node, ибо возвращаемое значение нигде не используется, тогда и тело метода в одну строчку можно будет записать.

2019-02-07 21:42 UTC, Xrite commented on 2-Trie/src/test/java/TrieTest.java
> +    void deserialize() {
@RamSaw, не очень понятно как их тестировать отдельно, ведь вся их суть в том, чтобы композиция давала id.

2019-02-08 12:34 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +    void deserialize() {
Про id согласен и на это нужен тест. Но представьте, что вы передаете этот Trie по сети. Вы договорились, что ваш Trie будет сериализован по определенному протоколу, это и надо проверить. В deserialize соответственно тоже. Ваша реализация может и будет давать id, но протокол может быть нарушен и получатель десериализует его неправильно.

2019-02-08 13:14 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +public class Trie extends AbstractSet<String> implements Serializable, Set<String> {
AbstractSet уже implements Set, поэтому можно убрать Set в объявлении.

2019-02-08 13:14 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +        if (o == null) {
Это всегда false, потому что !(null instanceof Trie) == true.

2019-02-08 13:14 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +        if (other.size == size && Objects.equals(other.root, root)) {
`return other.size == size && Objects.equals(other.root, root)`
Вообще я бы рекомендовал генерить equals и hashCode средствами IDEA.

2019-02-08 13:14 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +    public Iterator<String> iterator() {
Я бы убрал все же наследование от AbstractSet'a, идеологически конечно это правильно, но по заданию ваша структура не очень коррелирует со стандартномым интерфейсом Set. Как я понял, у вас перегружается только метод add, а все остальные отличаются от интерфейса Set. Ну методы кидающие UnsupportedOperationException не самая лучшая практика.

2019-02-08 13:14 UTC, RamSaw commented on 2-Trie/src/main/java/Trie.java
> +        public boolean equals(Object o) {
Те же замечания, что и для equals выше. Еще есть правило: всегда писать hashCode, если перегружаешь equals (https://stackoverflow.com/questions/2265503/why-do-i-need-to-override-the-equals-and-hashcode-methods-in-java).

2019-02-08 13:14 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +        simple.add("aba");
Кажется, можно просто двумя циклами проитерироваться по полю simpleStrings.

2019-02-08 13:31 UTC, RamSaw commented
@Xrite исправления проверил.

2019-02-09 15:10 UTC, Xrite commented
@RamSaw, добавил исправления

2019-02-13 08:41 UTC, RamSaw requested changes
@Xrite исправления проверил. Исправьте маленькие новые, пожалуйста, и думаю можно будет уже зачесть :)

2019-02-13 08:41 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +        for (int i = 7; i > 0; i--) {
Что такое 7? Видимо simpleStrings.size(), так и надо писать. Магические константы всегда очень плохо влияют на код.

2019-02-13 08:41 UTC, RamSaw commented on 2-Trie/src/main/java/UniterableSet.java
> +    default void removeAll(List<E> list) {
Протестируйте их тогда, пожалуйста, раз добавили. А то removeAll вообще нигде не используется.

2019-02-13 08:41 UTC, RamSaw commented on 2-Trie/src/test/java/TrieTest.java
> +    void checkDeserializeEmpty() throws IOException {
Протестируйте, пожалуйста, на маленьком боре еще каком-нибудь.

2019-02-18 23:01 UTC, Xrite commented
@RamSaw, добавил еще тесты.

2019-02-21 17:42 UTC, RamSaw approved these changes
Ок, мне все нравится. Передаю слово @jzuken .

2019-02-27 14:09 UTC, jzuken commented
конфликт с мастером, надо бы померджать

2019-03-07 12:05 UTC, merged