Hw3 mytreeset
Xrite/java-hw-2-course pull request #4
Opened 2019-02-09 15:15 UTC by Xrite

2019-02-24 17:40 UTC, RamSaw requested changes
@Xrite домашку проверил, жду исправлений

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/MyTreeSet.java
> +public interface MyTreeSet<E> extends Set<E> {
Тут не все методы протестированы.

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +        comparator = (Comparator<? super E>) Comparator.naturalOrder();
SuppressWarnings надо использовать.

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +        return data.root.size;
Тернарный оператор

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +    public E floor(E e) {
floor и lower можно выделить в общий метод и передавать влаг, включая или не включая данный элемент.

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +        Node() {
Конструктор не используется

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/test/java/ru/hse/aabukov/mytreeset/TreapTest.java
> +        assertDoesNotThrow(() -> objects.add(new Object()));
Эту лямбду можно вынести в отдельную переменную, так как она два раза используется.

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +        if (comparator.compare(first(), (E) o) == 0) {
Это не совсем верно, почитайте документацию по этому методу. Там должен проходить и обычный Object, а у Вас только тип E будет поддерживаться. Это касается всех методов принимающих Object.

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +    private Pair split(Node node, E element) {
Добавьте Nullable везде, где надо.

2019-02-24 17:40 UTC, RamSaw commented on 3-MyTreeSet/src/test/java/ru/hse/aabukov/mytreeset/TreapTest.java
> +        var empty = new Treap<String>();
не используется переменная

2019-02-26 16:55 UTC, Xrite commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/MyTreeSet.java
> +public interface MyTreeSet<E> extends Set<E> {
Это так и задуманно, так как их бессмысленно тестировать. Корректность этих методов следует из корректности других. Например для last это first и descendingSet.

2019-03-03 19:49 UTC, RamSaw requested changes
@Xrite Исправления проверил, жду исправлений.
Тимофей попросил вам говорить, если я снимаю баллы. 
Согласно критериям, что у меня есть, я снял -1 за критерий "contains в состоянии принять объект другого типа" и -0.5 за "@NotNull / @Nullable".
По поводу юнит-тестов, если Вы меня не переубедите, я буду снимать в будущем за это. В этой домашке не буду, так как Вы это делали осознанно и со своим смыслом.

2019-03-03 19:49 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
>      public E first() {
First не возвращает null, оно кидает исключение. То же самое применимо last.

2019-03-03 19:49 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +            throw new IllegalArgumentException("Objects that can not be cast to E are not supported");
contains и remove не просто так принимают object. Связано это с тем, что я иногда могу передать Object и научить его сравниваться с одним из родителей типа E. Тогда передав его сравнение будет определено, но при этом каст к E может не пройдет.

2019-03-03 19:49 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +            throw new IllegalArgumentException("Objects that can not be cast to E are not supported");
Напишите еще тестов на ту ситуацию, которую я описал.
Кстати случаи передачи компаратора и использования Comparable потенциально разные: к примеру во втором, null объекты не поддерживаются TreeSet.

2019-03-03 19:52 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/MyTreeSet.java
> +public interface MyTreeSet<E> extends Set<E> {
Смотрите, для меня одно из самых важных целей юнит-тестирования является гарантия того, что новые изменения не внесли ошибок. Особенно важно при рефакторинге. Когда большой проект и много кода, можно ненароком что-то поправить и сломать. А юнит-тесты дадут гарантию, что публичные интерфейсы, хоть и не на 100%, но работают. Тут методы реализованы просто, но все равно их надо протестировать. Раз они выражаются черех какие-то методы, которые Вы уже реализовали и протестровали, то наверное и тестировать их будет легче.

2019-03-09 11:23 UTC, Xrite commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
>      public E first() {
First может возвращать null, так null вполне может быть первым элементом.

2019-03-09 11:35 UTC, Xrite commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +            throw new IllegalArgumentException("Objects that can not be cast to E are not supported");
Научит сравниваться Object нельзя, так как все зависит от компаратора. Т.е. после того, как я засунул туда компаратор, я уже ничего не могу доопределить у других классов. А в описанной ситуации можно просто пользователю изначально создать MyTreeSet с другим типовым параметром, если он уж хочет сравнивать в таких ситуациях.

2019-03-09 21:17 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
>      public E first() {
А сори, там видимо дифф между коммитами не прогрузился и я подумал, что вы null возвращаете, если пустое множество. Так то конечно nullable, Вы правы.

2019-03-09 21:24 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +            throw new IllegalArgumentException("Objects that can not be cast to E are not supported");
Сейчас попробую объяснить более понятно. Вот Вы создали MyTreeSet<Integer>. А потом делаете следующее: MyString implements Comparable<Integer>. А компаратор такой: конвертим строку к числу и просто сравниваем, если строка не число, то она всегда меньше любого числа, к примеру. А теперь я передам MyString в contains и полностью валидно проверю, есть ли там такое число. Получу совершенно осмысленный true или false.
Безусловно, я согласен, это довольно странный случай использования и я лично на практике такое не писал и не видел, чтобы писали, но стандартный TreeSet так реализован и более того в этом домашнем задании достаточно интересно это реализовать, ведь это домашнее задание на дженерики, а не на то, что вы умеете писать деревья поиска. После курса Сережи, я думаю в этом никто не сомневается :)

2019-03-09 21:26 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +            throw new IllegalArgumentException("Objects that can not be cast to E are not supported");
Кстати, по поводу Travis: вы же можете в скрипте прописать обходить все директории в корне репозитория и запускать в них build. Не надо будет добавлять все время новые домашки и изменять Travis.

2019-03-13 19:37 UTC, Xrite commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +            throw new IllegalArgumentException("Objects that can not be cast to E are not supported");
А, ок, я понял. Вроде исправил. Travis потом настрою.

2019-03-15 14:57 UTC, RamSaw requested changes
@Xrite остались совсем мелочи, пофиксите, пожалуйста.

2019-03-15 14:57 UTC, RamSaw commented on 3-MyTreeSet/src/main/java/ru/hse/aabukov/mytreeset/Treap.java
> +     * Works like {@link TreeSet#contains(Object)}
однострочный коммент.

2019-03-15 14:57 UTC, RamSaw commented on 3-MyTreeSet/src/test/java/ru/hse/aabukov/mytreeset/TreapTest.java
> +        assertThrows(ClassCastException.class, newObject);
а почему тут бросается ClassCastException у add?

2019-03-15 22:07 UTC, Xrite commented on 3-MyTreeSet/src/test/java/ru/hse/aabukov/mytreeset/TreapTest.java
> +        assertThrows(ClassCastException.class, newObject);
Я здесь передаю несравнимые объекты. Если вопрос в том, почему ClassCastException вместо IllegalArgumentException, то я просто сделал как в TreeSet.

2019-03-17 17:29 UTC, RamSaw commented
Ок.
@jzuken

2019-03-18 17:26 UTC, merged