Hw4 db
Xrite/java-hw-2-course pull request #5
Opened 2019-02-26 16:42 UTC by Xrite

2019-03-16 14:32 UTC, RamSaw requested changes
@Xrite домашку проверил, жду исправлений. 
Там некоторые замечания много где повторяются, но к каждой строке, где это происходит, я не писал комментарий, писал только к одной, поэтому проверьте, что похожих замечаний не встречается в других строчках, пожалуйста.

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/build.gradle
> +plugins {
нет указания main class, как следствие запуск jar файла после билда невозможен.

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/Interactor.java
> + * Main class that interacts with user
однострочный комментарий

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/Interactor.java
> +
пустая строчка

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +    private @NotNull Long id;
думаете id ускорит работу mongoDB?

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +        id = nextId++;
а там нет в MongoDB что-то наподобие autoincrement?
мне кажется, что поддержание id как первичного ключа больше нужно для SQL-based баз данных. А Вы как думаете?

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +    public PersonData(@NotNull String name, @NotNull String number) {
package-private. всех мест касается, -0.5.

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/Interactor.java
> + * Main class that interacts with user
всех мест ниже тоже касается

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +        id = nextId++;
судя по комментам в джавадоках, там поддерживается какой-то внутренний id, по которому еще и можно удалять и другие операции делать.

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +    public PersonData() {
зачем такой конструктор? это MongoDB требует? если да, то так и напишите в джавадоке и тогда вопрос, а надо ли инкрементить id, если да, то почему?

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/PhoneDataBase.java
> +                .field("name").equal(name)
давайте вынесем эти строки в отдельные статические поля PersonData. Или же погуглите, может можно как-то их извлечь, учитывая то, что Вы на них поставили соответствующие аннотации.

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/test/java/ru/hse/aabukov/db/PhoneDataBaseTest.java
> +    final String[] sampleNames   = {"a", "a", "b", "b", "e", "f", "g", "a"};
private, -0.5

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/test/java/ru/hse/aabukov/db/PhoneDataBaseTest.java
> +        assertArrayEquals(new PersonData[] {new PersonData("b", "a"), new PersonData("b", "a")}, dataBase.allRecords().toArray());
слишком длинные строки

2019-03-16 14:32 UTC, RamSaw commented on 4-DB/src/test/java/ru/hse/aabukov/db/PhoneDataBaseTest.java
> +        assertArrayEquals(new PersonData[] {new PersonData("a", "a"), new PersonData("a", "a")}, dataBase.allRecords().toArray());
такое поведение я думаю не ожидается
в базе данных не должно быть одинаковых пар значений. А случилось это вероятно из-за того, что у них id разный.

2019-03-16 22:00 UTC, Xrite commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +    private @NotNull Long id;
Не знаю. Но насколько я понял, id обязательно должен быть, иначе не работатет. Вываливается ошибка, говорящая что он обязателен. Ну а другое поле не сделаешь id по понятным причинам.

2019-03-16 22:02 UTC, Xrite commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +        id = nextId++;
Пишут, что в mongoDB нет autoincrement.

2019-03-16 22:07 UTC, Xrite commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +    public PersonData(@NotNull String name, @NotNull String number) {
Не очень понял, то есть вообще все (все классы и публичные методы) должно быть package-private? Имеется в виду, что мы предполагаем, что наши классы изолированны, и никто их не будет использовать, или что? Просто тогда во всех домашках стоило делать все package-private.

2019-03-16 22:15 UTC, Xrite commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +    public PersonData() {
Да, для morphia требуется конструктор по умолчанию. Да, надо инкрементить, иначе будут затираться старые значения.

2019-03-16 22:20 UTC, Xrite commented on 4-DB/src/test/java/ru/hse/aabukov/db/PhoneDataBaseTest.java
> +        assertArrayEquals(new PersonData[] {new PersonData("a", "a"), new PersonData("a", "a")}, dataBase.allRecords().toArray());
Нет, такое поведение ожидается. Я даже специально это в тесте проверяю. В задании не было явно сказано как обрабатывать ситуации, когда добавляется такой же, так что я считаю, что сделал все законно. Данное поведение обосновано тем, что у нас может несколько людей иметь одинаковый номер, но так же могуть быть и люди с одинаковым именем (что вполне естественно). Так что это остается на пользователе, что с этим делать. Он может давать им какую-то приписку к имени, чтобы была однозначность.

2019-03-19 21:53 UTC, RamSaw commented on 4-DB/src/test/java/ru/hse/aabukov/db/PhoneDataBaseTest.java
> +        assertArrayEquals(new PersonData[] {new PersonData("a", "a"), new PersonData("a", "a")}, dataBase.allRecords().toArray());
ок, в задании действительно не сказано.
многие реляционные СУБД кстати позволяют так делать.

2019-03-19 22:14 UTC, RamSaw requested changes
@Xrite все ок.
public поправьте или, если я не убедил, то давайте обсуждать.

2019-03-19 22:14 UTC, RamSaw commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +    public PersonData(@NotNull String name, @NotNull String number) {
Не, смотрите. Когда вы писали библеотечные классы, было бы странно делать их интерфейс package-private (не случайно все методы в интерфейсе всегда публичные). Здесь Вы пишете конечное приложение, смысла делать публичными их нет. Всегда лучше сузить видимость, если понадобиться больше, то подумать, а надо ли действительно ее расширять, а потом уже только расширить. Это скорее не вопрос о джаве, а о практиках проектирования ПО.

2019-03-20 11:43 UTC, Xrite commented on 4-DB/src/main/java/ru/hse/aabukov/db/PersonData.java
> +    public PersonData(@NotNull String name, @NotNull String number) {
Хорошо, исправил.

2019-03-20 14:58 UTC, jzuken requested changes

2019-03-20 14:58 UTC, jzuken commented on 4-DB/src/main/java/ru/hse/aabukov/db/PhoneDataBase.java
> +        datastore.delete(byNameAndNumberQuery(name, number));
а если такой пары нет, оно просто молчит. и если вы пытаетесь добавить два раза одно и то же, оно молча добавляет и тоже молчит. приложение не должно молчать, это неправильная ситуация, нужно всегда как-то реагировать на них
-0.5

2019-03-20 20:06 UTC, Xrite commented on 4-DB/src/main/java/ru/hse/aabukov/db/PhoneDataBase.java
> +        datastore.delete(byNameAndNumberQuery(name, number));
Это же никак не было указано в задании.

2019-03-21 19:33 UTC, jzuken commented on 4-DB/src/main/java/ru/hse/aabukov/db/PhoneDataBase.java
> +        datastore.delete(byNameAndNumberQuery(name, number));
это общая культура программирования, в задании вообще много чего не сказано

2019-03-21 19:34 UTC, merged