Hw5 reflector
Xrite/java-hw-2-course pull request #8
Opened 2019-03-13 00:08 UTC by Xrite

2019-03-17 18:55 UTC, jzuken requested changes

2019-03-17 18:55 UTC, jzuken commented on 5-Reflector/src/main/java/ClassPrinter.java
> +        if (clazz.equals(char.class)) {
ну вы хоть бы объединили их что ли. и else-if использовали

2019-03-17 18:55 UTC, jzuken commented on 5-Reflector/src/test/java/ComplexClass2.java
> +public class ComplexClass2<T extends Integer> {
положите их в отдельный пакет лучше, чтобы они не путались с тестовыми классами

2019-03-20 11:40 UTC, Xrite commented on 5-Reflector/src/test/java/ComplexClass2.java
> +public class ComplexClass2<T extends Integer> {
Вроде исправил.

2019-03-20 14:52 UTC, jzuken commented
и тут внезапно конфликты с мастером начинают намекать, что эта ветка растёт не оттуда, откуда положено. и теперь нужно создать новую ветку от мастера и перебазировать (git rebase) туда все нужные коммиты. 
-1

2019-04-29 12:46 UTC, merged